### ISSUE TITLE
failed  to flush to storage

### ISSUE THREAD

**Issue by bestHandsome** [rodrigoelicer/electron-testing-app-2#1]
i use this method to run my project, but i get an error  
![image](https://user-images.githubusercontent.com/19648679/35203367-d4ecc078-ff62-11e7-8b90-1965a60bf99b.png)

**Comment by rodrigoelicer** [comment]
It's hard to tell because I did this 1 year ago. However I downloaded the repository again and it run well for me. Did you do something to the code? Or just executed right away after cloning it?

**Comment by bestHandsome** [comment]
well,  i downloaded your repository, it run well too, but in my project i get this error,  i think it's my problem , i use it in angular5, i find some methods to resolve it ,thanks a lot.
